### ISSUE TITLE
Deepstream Analytics Source Code Review

### ISSUE THREAD

**Issue by suraj-ajjampur** [cu-ecen-aeld/final-project-Suraj-Ajjampur#2]
The [application repository](https://github.com/cu-ecen-aeld/deepstream-nvdsanalytics-docker) we are leveraging needs to be reviewed to further our understanding for our final application. This review would involve going through NVIDIAs documentation for configurations, an overview of the code setup used. This would include analysis of the the docker setup used and the src directory which consists of source files which serve as the application along with configuration files used in the process of building the final application.

This code is pushed into the following repo which will serve as the application source code repo: https://github.com/cu-ecen-aeld/final-project-Suraj-Ajjampur

Dod:
Analysis of the following:
- [x] docker Directory

And the src directory, mainly targetting: 
- [x] Makefile.ds
- [x] cfg-deepstream-default directory
- [x] cfg-model-default
- [x] initScript.sh
- [x] deepstream_app_main.c

Blocker: The base application source code has less comments. A thorough review is needed to progress.

**Comment by Suraj-Ajjampur** [comment]
Created a fork of the [Repo](https://github.com/Suraj-Ajjampur/deepstream-nvdsanalytics-docker) here. We shall be improving the documentation and making our changes here which can later be merged with the main repository if approved.

**Comment by aasu8675** [comment]
The code review analysis is given below:

# Docker directory

- The build.sh script is used to build a docker container with an Image called deepstream-nvdsanalytics-docker. As we run our application on the Jetson nano, the docker build uses the Dockerfile.Jetson for configuration
- Dockerfile.Jetson consists of the necessary packages used to build the application source files, it uses CUDA version 10.2 and calls Makefile.ds to build the executable. The docker container starts with an entry point by using a initScript.sh present in the src file.
- The run.sh script checks for a data mount and runs the docker container with the host(Jetson) network stack

# SRC Directory
## cfg-deepstream-default
cfg-deepstream-default directory consists of multiple txt files which are used for configuration. 
- bai_config_nvdsanalytics.txt: This file is used to set properties on the stream. It gives details on the type of filtering done. There are multiple streams present, only one ROI filtering stream is active which detects all classes. Th overcrowding stream is disabled. A line crossing stream is used, which allows us to set a line on the frame based on which some useful analysis can be performed. This would be crucial for over next sprints.
The direction detection stream present is for detection of the direction for class-id 0 (person), and it is disabled
- bai_deepstream.txt: This file is used to configure the multiple settings for the application, the display, the GPU selected, the source and sink configurations. This file is essential for the next sprints as it will gives us the flexibility to change our source and sink which is part of the future work.

This file uses the tracker_config.yml for tracker properties and sets the config file (bai_config_nvdsanalytics.txt) for analytics which was analyzed earlier.
- tracker_config.yml: This yaml file contains informations about the way the AI model works. The weights for necessary feature extraction computation, data association, state estimator is present in this file. 
 
## cfg-model-default
 - This directory consists of a file called labels.txt which gives a list of Objects which can be analyzed as part of this deepstream application. This file is used while performing stream filtering. 
 
## Makefile.ds
- This makefile consists of the all the required sources. libraries, packages required to build the application "deepstream-app". 

## initScript.sh
- This script checks for an input video in the /input directory, if its not found it copies a sample video and sets the ouput directory and runs the deepstream-app with necessary configurations for the application.

## deepstream_app_main.c
- This c file serves as the main application for the deepstream application being built. It has additional functions for handling meta-deta, performance metrics printing, interrupt handling.
