### ISSUE TITLE
Sprint 2 - Change camera input and RTSP output stream for a custom application

### ISSUE THREAD

**Issue by aasu8675** [cu-ecen-aeld/final-project-Suraj-Ajjampur#4]
DoD:

- [x] Update config files to test out a camera and the RTSP sink.
- [x] Create a scenario for final application, and define the boundaries for a security system which gives count of people in restricted area.

Blockers:
Need to check feasiblility of multiple streams to configure the count. 
Need to test out the procured camera and check for its working.

**Comment by suraj-ajjampur** [comment]
Configuration files changed at [deepstream_app_main.c](https://github.com/cu-ecen-aeld/final-project-Suraj-Ajjampur/blob/main/src/deepstream_app_main.c)
